name: deep-learning
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - jupyter=1.0.0
  - pytorch=1.11.0
  - torchinfo=1.7.0
  - jupyter=1.0.0
  - pillow=9.0.1
  - opencv=4.5.5
  - pandas=1.4.2
  - matplotlib=3.5.2
  - scikit-learn=1.1.1
  - imageio=2.19.3
  - scipy=1.8.1

